version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
        - name: sales
          identifier: raw_gz_sales
        - name: raw_gz_product
          identifier: raw_gz_product
        - name: raw_gz_ship
          identifier: ship